server:
  port: 8090

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: http://117.72.44.202:8000/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTcyMDMzMjE2MiwiaWF0IjoxNzEyNTU2MTYyLCJqdGkiOiJjbzlvaDBrdWR1NmM1am80bzJvMCIsInR5cCI6InJlZnJlc2giLCJzdWIiOiJjbzlvOWdxbG5sOTBiNzZ0ZnNrZyIsInNwYWNlX2lkIjoiY250dW50cGtxcTRqOWxnZDYwazAiLCJhYnN0cmFjdF91c2VyX2lkIjoiY250dW50cGtxcTRqOWxnZDYwamcifQ._A9y7uEF41jkq2M9sgYFtQe7GeZYwL9MN0UgEYjEkVi1_Md_msrtD7r4HEUWVCgiTcRUH1Bs8WOHKcoYrLh13A

app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy