server:
  port: 8090

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: http://117.72.44.202:8000/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1c2VyLWNlbnRlciIsImV4cCI6MTcyMDMzMjE2MiwiaWF0IjoxNzEyNTU2MTYyLCJqdGkiOiJjbzlvaDBrdWR1NmM1am80bzJvMCIsInR5cCI6InJlZnJlc2giLCJzdWIiOiJjbzlvOWdxbG5sOTBiNzZ0ZnNrZyIsInNwYWNlX2lkIjoiY250dW50cGtxcTRqOWxnZDYwazAiLCJhYnN0cmFjdF91c2VyX2lkIjoiY250dW50cGtxcTRqOWxnZDYwamcifQ._A9y7uEF41jkq2M9sgYFtQe7GeZYwL9MN0UgEYjEkVi1_Md_msrtD7r4HEUWVCgiTcRUH1Bs8WOHKcoYrLh13A

app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    limit-count: 3
    white-list: wxd8c3c4617d93a08f

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

wx:
  config:
    originalid: gh_69ff7daf9c33
    appid: wxd8c3c4617d93a08f
    token: q1w2

# 数据库配置；SpringBoot 默认连接池为 HikariDataSource
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://117.72.44.202:3306/aigc?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000136622735
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCGCHxOa1L3s0EBelydSmHaba14og+Tt8yV+C3aHNHRUHQlxTcI+qsU4sALa9iy21c4QDOLPbmUznMMQtwUA3KTsXHNEtN2azn4YXMNbR5Si5P0baGc2N8gqW1aFv87uNS3HmZy1cnnp67tG2aRup/1zIZ+y85ivaihFn7MK9wuG4/jDQcK9O8c+Dww//8umT6izmivwSMusU/QqTXmm7rOZxmcG+I3dakHf8Pg8qLxhpmqLYgfEMqr9D4R4i/Rl3erN7pnZlGUXq8IqoGwRMhnmvs1SsSSZfXztFOAJQGlje64HnJnxp5Mc2nrQB0LNGdOV+Vob3v5Ow3UpMyg25xBAgMBAAECggEARCeadhHS7Yuj+YlsALtrCLQOqrHVs+qZSIUbY7aV5pa/iNlAw/sa9ZLbzrL3TPOF5V+YFiy76nQUQl7ZJAAgygNH99yj1KpvnuKGq4QaECVThc4diPEqfKRKq63X+VliKP93XtthQL+ejokJXf8FCesHVQBzoPgKAGe88Ds5SeQShFYQHCnqFmZIj0uSzM3UG01S5vEdv0nxE6geKmOq1+CRVENEuwPvPp/lHo/hsZJK5DB/7OCWN8TXZXERFAecsrnXwf1XVnoPfGswkxE09dLFtJS0tO/bL3Tn0aYZTvCN1JO1YVC6UoMgCDh4s558DL1zp5Mf+8SsWwJNxX1UwQKBgQDOkAvOE7TUY9bS2Lsq/dHuR/mh3tkOINPtduQc4eJLDTf+cHR5NZnBtj5zJlA7CfnKq3y8SABIq8a2unzsjfQxjQ+/SnAXaCwOm3UW8QRbgHlkzUCt0hpZ84CE9ayTpKqa5kCu/rOgc2iORXmdm4TDUKJN0SrHJUJRYuY5MB9jOQKBgQCmHJrJ0nI2LQpIE+At+0rOVllrNQRoak3ApEKPan7n/OR1lokc3KSFyodOqrHEi4NXRLlCxsB4Goi4MESaWIEXaLxcda/vZfKHbQrKQSGuoQ8MB31oW+NpLrc4I9cxtyhxhF/lN+i4hELkt53adWpWO6EjzRT5a7Mq7ZpH0jXZSQKBgQCE+skOxzMAFLJFFRAR0kvnGeEEq6GS7eFhm8upKGZ1qLHmlOD282HkCn5TxVObXoW4SwRHdhbwsd2A37fy1kRh7g04OiTFfOP4F26e8VS7z47XLSg5fuxGAnQ3pK2Qc07938O+pOxhHEswZFux8l/bGbsTW9gtUrhKCuBp6qgaSQKBgQCdMzLVToBhfsxdG9orCcZocNVcnKbYPcnpRknrOWhyGSUHlveZRcG5D8pvCyEClNkuDE6awEbDIrFCRgOWYa2BPtALXCCsmTklKm9sqqi6f5ci1i+7REJ5dwlTaq+rT99JVnH+FaP6gshfdNlBNZ71jqbXn6x6wo6jUIqR74CgaQKBgFEyQovaXI1Ds8vCpDelHE5h2Zt1bvha6Qva2Ng8wSK2D9diwlgSxqpyRrwqXFgsCq1HzF/uInMDvvbh2f+zGefEki7ofFp/qIsuVUszQuRL4F5IfE3d8/vuHzRnxpO9p/I9qVXBsEJBYSkHyR5j0XuBAc1AY2A9rwLKLCeJ8L2a
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoA9DNgs4AO89Y6w6PdRycuz9HamTTBmMmYR1Xv8dvY7Yrkk1m7FRAW9QK9lBzL9ZFaf6WTPgJ3MdGIu1vhFWf4wiwk9BjQyTrGX/eUTyczuRb+AiOaaEIv3a/eZVRIQ6hR2YaUz2liwGfD+cyKNduh3KL6Xmb8wDDf2CBoG8TbEQ9KUuL7eVtCco3AVj/x/V7VaJ2Mat6/dF9fiAkcCM9UGfzKWVdUKJ/xZRePEZ/iO8AtjnBFY6AKTKMp9p2XPGBGfvM5LrhZUuBIT0qLEO5Inr9UuGWNBratfekoWUVKz+ygdROb9ZrrbWEtQWwMZJdTkXVEJtL5fDrIYTY/AELQIDAQAB
  notify_url: http://api.aishuijiao.xyz/api/v1/sale/pay_notify
  return_url: http://aigc.aishuijiao.xyz
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
