server:
  port: 8090

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://gpt35.allai.works/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-usywctCXPkAOxhirR5hXxYmNwjBKrycHiAD5P4Iq80ZpZQB8

app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy